
export enum ModalType {
  SUCCESS = "SUCCESS",
  REDEEM_PROGRESS = "REDEEM_PROGRESS",
  JOIN_WECHAT = "JOIN_WECHAT",
  SHARE = "SHARE",
  CONNECT_WALLET = "CONNECT_WALLET",
  TRANSFER = "TRANSFER",
  LOADING = "LOADING",
}